server:
  port: 9000

spring:
  application:
    name: "config"
  cloud:
    config:
      server:
        git:
          uri: "file:///home/darek/Devel/Spring/spring-io-lab15-config"

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
