spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_PORT_3306_TCP_ADDR:localhost}:${MYSQL_PORT_3306_TCP_PORT:3306}/store?autoReconnect=true&useSSL=false"
    username: "root"
    password: "sprio"
  jpa:
    hibernate:
      ddl-auto: "validate"

uri:
  customizer:
    rewrite:
      warehouse:
        host: "localhost"
        port: 9100
      marketing:
        host: "localhost"
        port: 9120
