info:
  year: 2018
  company: "Vattenfall"

spring:
#  profiles:
#    active: "h2"
  jackson:
    serialization:
      indent-output: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"

---

spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRES_PORT_5432_TCP_ADDR:localhost}:${POSTGRES_PORT_5432_TCP_PORT:5432}/${POSTGRES_DB:warehouse}"
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PASSWORD:sprio}"
  jpa:
    hibernate:
      ddl-auto: "validate"
